plugins:
  - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.1"
      repository: "https://maven.lavalink.dev/releases" 
      snapshot: false  
  lavasrc:
    providers: 
      # - "dzisrc:%ISRC%" 
      # - "dzsearch:%QUERY%" 
      - "ytsearch:\"%ISRC%\"" 
      - "ytsearch:%QUERY%" 
    sources:
      spotify: false # Enable Spotify source
      applemusic: false # Enable Apple Music source
      deezer: false # Enable Deezer source
      yandexmusic: false # Enable Yandex Music source
      flowerytts: false # Enable Flowery TTs source
      youtube: true 
    spotify:
      clientId: "your client id"
      clientSecret: "your client secret"
      countryCode: "US" 
      playlistLoadLimit: 6 # 
      albumLoadLimit: 6 
    applemusic:
      countryCode: "US" 
      mediaAPIToken: "..." 
      playlistLoadLimit: 6 
      albumLoadLimit: 6 
    deezer:
      masterDecryptionKey: "your master decryption key" 
    yandexmusic:
      accessToken: "your access token" 
    flowerytts:
      voice: "default voice" 
      translate: false 
      silence: 0 
      speed: 1.0 
      audioFormat: "mp3" 

server: # REST and WS server
  port: 2333
  address: 0.0.0.0
lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0
    q"
  server:
    password: "prince24"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400 
    frameBufferDurationMs: 5000 
    opusEncodingQuality: 0 
    resamplingQuality: LOW .
    trackStuckThresholdMs: 10000 
    useSeekGhosting: true 
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
